### ISSUE TITLE
Livechan broken, halp pls!

### ISSUE THREAD

**Issue by devqts** [majestrate/livechan#1]
We can't attach any file to post, it only return

> could not process file at this time (probably server stress)
> fix it please, be kind to us ;-;

And Anna wikibot ded too, would be nice if we meet her again. Thx.

**Comment by majestrate** [comment]
if this is for livechan.net you may want to submit an issue to https://github.com/emgram769/live4chan instead.

**Comment by devqts** [comment]
oh, sorry to trouble you.
